export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', background: '#211f1d', color: '#ddd', fontFamily: 'Segoe UI, sans-serif' }}>
      <div style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px', lineHeight: 1.7 }}>
        <h1 style={{ color: '#fff' }}>Terms & Conditions</h1>
        <p style={{ color: '#999', fontSize: 13 }}>Last updated: September 2026</p>

        <h3 style={{ color: '#F0801E' }}>1. About Machinest Studio</h3>
        <p>Machinest Studio ("we", "us") is operated in connection with machinest.in and provides web-based CNC programming tools, including cycle/G-code generators, on a membership (subscription) basis to individuals and businesses.</p>

        <h3 style={{ color: '#F0801E' }}>2. Membership & Billing</h3>
        <p>Access to individual tools within Machinest Studio is sold on a recurring subscription basis. Prices for each tool are displayed within the app at the time of purchase and may change from time to time. Continued use after a price change constitutes acceptance of the new price for future billing cycles.</p>

        <h3 style={{ color: '#F0801E' }}>3. No Warranty on Generated Output</h3>
        <p>All G-code, NC programs, and other output generated by Machinest Studio tools are provided for reference and convenience only. You are solely responsible for verifying every generated program &mdash; through simulation, dry-run, or manual review &mdash; before running it on any machine. We are not liable for any damage to machines, tooling, material, or injury resulting from the use of generated programs.</p>

        <h3 style={{ color: '#F0801E' }}>4. Account Responsibility</h3>
        <p>You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account.</p>

        <h3 style={{ color: '#F0801E' }}>5. Cancellation & Refunds</h3>
        <p>See our <a href="/refund" style={{ color: '#F0801E' }}>Refund & Cancellation Policy</a> for details.</p>

        <h3 style={{ color: '#F0801E' }}>6. Changes to Service</h3>
        <p>We may add, modify, or remove tools and features at any time. We may suspend or terminate accounts that misuse the platform.</p>

        <h3 style={{ color: '#F0801E' }}>7. Contact</h3>
        <p>For any questions regarding these terms, contact us through the details listed on machinest.in.(+91-7988277215)</p>
      </div>
    </div>
  )
}